import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGES_DIR = resolve(ROOT_DIR, 'packages');
const ROOT_PACKAGE_JSON = resolve(ROOT_DIR, 'package.json');

const DEFAULT_SCOPE = '@agrimetrics';

const toKebabCase = (value) =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

const parseArguments = () => {
  const args = process.argv.slice(2);
  const rawName = args.find((arg) => !arg.startsWith('--'));

  if (!rawName) {
    throw new Error('Usage: pnpm run new:package -- <package-name> [--scope=@agrimetrics]');
  }

  const scopeArg = args.find((arg) => arg.startsWith('--scope='));
  const scope = scopeArg ? scopeArg.split('=')[1] : DEFAULT_SCOPE;

  if (!scope.startsWith('@')) {
    throw new Error('Scope must start with @, for example --scope=@agrimetrics');
  }

  const directoryName = toKebabCase(rawName);

  if (!directoryName) {
    throw new Error('Package name cannot be empty after normalization');
  }

  return {
    directoryName,
    packageName: `${scope}/${directoryName}`,
  };
};

const packageJsonTemplate = ({ packageName, directoryName }) => `{
  "name": "${packageName}",
  "version": "0.0.0",
  "private": false,
  "type": "module",
  "engines": {
    "node": ">=24.12.0"
  },
  "description": "${directoryName} package — DSP Toolkit",
  "sideEffects": false,
  "main": "dist/index.js",
  "module": "dist/index.js",
  "types": "dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js"
    }
  },
  "files": [
    "dist",
    "README.md"
  ],
  "scripts": {
    "clean": "rm -rf dist",
    "build": "vite build",
    "typecheck": "tsc --noEmit",
    "lint": "eslint './src/**/*.{js,ts}'",
    "lint:fix": "eslint './src/**/*.{js,ts}' --fix",
    "format": "prettier --write \"./src/**/*.{ts,json}\"",
    "format:check": "prettier --check \"./src/**/*.{ts,json}\"",
    "test": "vitest",
    "test:ci": "vitest run --passWithNoTests",
    "release": "semantic-release",
    "quality:ci": "pnpm run lint && pnpm run format:check && pnpm run typecheck && pnpm run test:ci && pnpm run build"
  },
  "devDependencies": {
    "@dsp-toolkit/shared-config": "workspace:*",
    "@dsp-toolkit/typescript-config": "workspace:*",
    "@tpzdsp/eslint-config-dsp": "^4.0.0",
    "@types/node": "^24.12.2",
    "@typescript-eslint/eslint-plugin": "^8.58.0",
    "@typescript-eslint/parser": "^8.58.0",
    "eslint": "^9.39.4",
    "prettier": "^3.8.1",
    "semantic-release": "^25.0.2",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/github": "^12.0.2",
    "typescript": "^6.0.2",
    "vite": "^8.0.8",
    "vite-plugin-dts": "^4.5.4",
    "vitest": "^4.1.2"
  },
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  }
}
`;

const tsconfigTemplate = `{
  "extends": "../../packages/typescript-config/library.json",
  "compilerOptions": {
    "types": ["node", "vitest/globals"],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["src"],
  "exclude": [
    "node_modules",
    "dist",
    "eslint.config.ts",
    "prettier.config.ts",
    "release.config.ts",
    "vite.config.ts"
  ]
}
`;

const eslintTemplate = `import { createLibraryEslintConfig } from '@dsp-toolkit/shared-config/eslint';

export default createLibraryEslintConfig({
  globals: {
    process: 'readonly',
  },
});
`;

const prettierTemplate = `import prettierConfig from '@dsp-toolkit/shared-config/prettier';

export default prettierConfig;
`;

const releaseTemplate = ({ directoryName }) => `import releaseConfig from '@dsp-toolkit/shared-config/release';

export default {
  ...releaseConfig,
  tagFormat: '${directoryName}-v\${version}',
};
`;

const viteTemplate = `import { createSimpleLibraryViteConfig } from '@dsp-toolkit/shared-config/vite';

export default createSimpleLibraryViteConfig(import.meta.url);
`;

const readmeTemplate = ({ packageName }) => `# ${packageName}

Package generated by DSP Toolkit scaffold.

## Scripts

- pnpm build
- pnpm lint
- pnpm test:ci
`;

const indexTemplate = `// Replace with real exports during migration.
export {};
`;

const smokeTestTemplate = ({ packageName }) => `import * as pkg from './index';

// Smoke tests: verify the package resolves and exports cleanly.
// Todos are stubs to implement after source migration.

describe('${packageName}', () => {
  it('resolves the package entrypoint', () => {
    expect(pkg).toBeDefined();
  });

  it.todo('exports a primary class or function');
});
`;

const updateRootScripts = ({ directoryName, packageName }) => {
  const rootPackage = JSON.parse(readFileSync(ROOT_PACKAGE_JSON, 'utf8'));
  const scripts = rootPackage.scripts ?? {};

  const qualityScriptName = `quality:ci:${directoryName}`;
  const releaseScriptName = `release:${directoryName}`;

  scripts[qualityScriptName] = `pnpm run quality:ci -- --filter=${packageName}`;
  scripts[releaseScriptName] = `pnpm --filter ${packageName} exec semantic-release`;

  rootPackage.scripts = scripts;
  writeFileSync(ROOT_PACKAGE_JSON, `${JSON.stringify(rootPackage, null, 2)}\n`);
};

const writePackageFiles = ({ directoryName, packageName }) => {
  const packageDir = resolve(PACKAGES_DIR, directoryName);

  if (existsSync(packageDir)) {
    throw new Error(`Package directory already exists: ${packageDir}`);
  }

  mkdirSync(resolve(packageDir, 'src'), { recursive: true });

  writeFileSync(resolve(packageDir, 'package.json'), packageJsonTemplate({ packageName, directoryName }));
  writeFileSync(resolve(packageDir, 'tsconfig.json'), tsconfigTemplate);
  writeFileSync(resolve(packageDir, 'eslint.config.ts'), eslintTemplate);
  writeFileSync(resolve(packageDir, 'prettier.config.ts'), prettierTemplate);
  writeFileSync(resolve(packageDir, 'release.config.ts'), releaseTemplate({ directoryName }));
  writeFileSync(resolve(packageDir, 'vite.config.ts'), viteTemplate);
  writeFileSync(resolve(packageDir, 'README.md'), readmeTemplate({ packageName }));
  writeFileSync(resolve(packageDir, 'src/index.ts'), indexTemplate);
  writeFileSync(resolve(packageDir, 'src/index.test.ts'), smokeTestTemplate({ packageName }));
};

try {
  const config = parseArguments();
  writePackageFiles(config);
  updateRootScripts(config);

  console.log(`Created package ${config.packageName} in packages/${config.directoryName}`);
  console.log('Next steps:');
  console.log('1) pnpm install');
  console.log(`2) pnpm run quality:ci:${config.directoryName}`);
  console.log('3) Add package to .github/workflows/release.yml options and ALL_PACKAGES when it should be releasable');
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`new:package failed: ${message}`);
  process.exit(1);
}
